---

- block:
  - name: Load alertx variables.
    include_vars: "../defaults/alertx.yml"

  - name: Downloading nodejs package
    get_url:
      url: "{{ alertx_noarch_nodejs_repository }}/{{ alertx_gui_nodejs }}"
      dest: "{{ trix_ood }}/3.0/alertx/{{ alertx_gui_nodejs }}"

  - name: Unpack nodejs files
    unarchive:
      src: "{{ trix_ood }}/3.0/alertx/{{ alertx_gui_nodejs }}"
      dest: "{{ trix_ood }}/3.0/alertx/app/assets/"
      keep_newer: false # override?

  - name: Cleanup nodejs package
    file:
      path: "{{ trix_ood }}/3.0/alertx/{{ alertx_gui_nodejs }}"
      state: absent
  when: ansible_connection not in 'chroot'
