# ---
# - name: Install Code Server on the controller
#   when:
#     - on_controller|default(False)
#     - ansible_connection not in 'chroot'
#   block:

#     - name: Make app folders for Code Server
#       ansible.builtin.file:
#         path: "{{ ood_apps_path }}/bc_codeserver/{{ item.path }}"
#         state: directory
#         owner: root
#         group: root
#         mode: "0755"
#       notify: Run update_ood
#       with_community.general.filetree: 
#       - templates/codeserver/app
#       - files/codeserver/app
#       when: item.state == 'directory'

#     - name: Copy app files for Code Server
#       ansible.builtin.copy:
#         src: "{{ item.src }}"
#         dest: "{{ ood_apps_path }}/bc_codeserver/{{ item.path }}"
#         mode: "0644"
#         owner: root
#         group: root
#       notify: Run update_ood
#       with_community.general.filetree: 
#       - files/codeserver/app
#       when: item.state == 'file'

#     - name: Render app files for Code Server
#       ansible.builtin.template:
#         src: "{{ item.src }}"
#         dest: "{{ ood_apps_path }}/bc_codeserver/{{  item.path | regex_replace('[.]j2$', '') }}"
#         mode: "0644"
#         owner: root
#         group: root
#       notify: Run update_ood
#       with_community.general.filetree: 
#       - templates/codeserver/app
#       when: item.state == 'file'

#     - name: Render module file for Code Server
#       ansible.builtin.template:
#         src: codeserver/module.lua.j2
#         dest: "{{ trix_shared }}/modulefiles/ood-codeserver.lua"
#         mode: "0644"
#         owner: root
#         group: root
#       notify: Run update_ood
#       when: "'codeserver/module.lua.j2' is exists"



# - name: Install Code Server 4.89.0 for Rhel
#   when:
#     - ansible_connection in 'chroot'
#     - ansible_facts['os_family'] == "RedHat"
#   block:
#     - name: Install Code Server 4.89.0 rpm
#       ansible.builtin.dnf:
#         name: https://github.com/coder/code-server/releases/download/v4.89.0/code-server-4.89.0-amd64.rpm
#         disable_gpg_check: true
#         state: present
#       retries: "{{ rpm_retries | default(3) }}"
#       delay: "{{ rpm_delay | default(15) }}"

# - name: Install Code Server 4.89.0 apt
#   when:
#     - ansible_connection in 'chroot'
#     - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#   block:
#     - name: Install Code Server 4.89.0
#       ansible.builtin.apt:
#         deb: https://github.com/coder/code-server/releases/download/v4.89.0/code-server_4.89.0_amd64.deb
#         state: present
