---
- name: Run task for OOD infiniband app
  when:
    - not in_image
  block:

  - name: Set permissions for inifinband related apps
    ansible.builtin.file:
      path: /dev/infiniband/umad0
      mode: "0660"
      owner: root
      group: "{{ ood_apps_admin_group }}"
    when: "'/dev/infiniband/umad0' is exists"

