# ---
# - name: Install Jupyter Notebook on the controller
#   when:
#     - on_controller|default(False)
#     - ansible_connection not in 'chroot'
#   block:
#     - name: Make app folders for VNC Desktop
#       ansible.builtin.file:
#         path: "{{ ood_apps_path }}/bc_jupyter/{{ item.path }}"
#         state: directory
#         owner: root
#         group: root
#         mode: "0755"
#       notify: Run update_ood
#       with_community.general.filetree: 
#       - templates/jupyter/app
#       - files/jupyter/app
#       when: item.state == 'directory'

#     - name: Copy app files for VNC Desktop
#       ansible.builtin.copy:
#         src: "{{ item.src }}"
#         dest: "{{ ood_apps_path }}/bc_jupyter/{{ item.path }}"
#         mode: "0644"
#         owner: root
#         group: root
#       notify: Run update_ood
#       with_community.general.filetree: 
#       - files/jupyter/app
#       when: item.state == 'file'

#     - name: Render app files for VNC Desktop
#       ansible.builtin.template:
#         src: "{{ item.src }}"
#         dest: "{{ ood_apps_path }}/bc_jupyter/{{  item.path | regex_replace('[.]j2$', '') }}"
#         mode: "0644"
#         owner: root
#         group: root
#       notify: Run update_ood
#       with_community.general.filetree: 
#       - templates/jupyter/app
#       when: item.state == 'file'

#     - name: Render module file for VNC Desktop
#       ansible.builtin.template:
#         src: jupyter/module.lua.j2
#         dest: "{{ trix_shared }}/modulefiles/ood-jupyter.lua"
#         mode: "0644"
#         owner: root
#         group: root
#       notify: Run update_ood
#       when: "'jupyter/module.lua.j2' is exists"



# - name: Install jupyter notebook on the compute nodes
#   block:
#     - name: Install python3-pip dependency for Jupyter Notebook
#       ansible.builtin.apt:
#         name:
#           - python3-pip
#           - python3-venv
#         state: present
#         update_cache: true
#       when: ansible_facts['os_family'] == 'Debian'

#     - name: Install python3-pip dependency for Jupyter Notebook
#       ansible.builtin.dnf:
#         name: python3-pip
#         state: present
#         disable_gpg_check: true
#       when: ansible_facts['os_family'] == "RedHat"
#       retries: "{{ rpm_retries | default(3) }}"
#       delay: "{{ rpm_delay | default(15) }}"

    # - name: Create Python virtual environment for Jupyter Notebook
    #   ansible.builtin.command: python3 -m venv /opt/ood-jupyter-python
    #   register: venv_output
    #   changed_when: venv_output.rc != 0
    #   when: ansible_connection in 'chroot'
