---
- name: Prepare login image for OOD installation
  when: in_login_image|default(False)
  block:
    - name: Render login-node-ood-prepare script
      template:
        src: 'login/login-node-ood-prepare-script.j2'
        dest: '{{ trix_sbin }}/login-node-ood-prepare.sh'
        owner: root
        group: root
        mode: 0750

    - name: Render /etc/systemd/system/luna2-daemon.service
      template:
        src: 'login/login-node-ood-prepare-service.j2'
        dest: '/etc/systemd/system/login-node-ood-prepare.service'
        owner: root
        group: root
        mode: 0644

    - name: Populate service facts
      service_facts:

    - name: Enable post boot login services for OOD preparation 
      service:
        name: 'login-node-ood-prepare'
        state: stopped
        enabled: true

    - name: Ensure '{{ ood_apps_admin_group }}' group exists
      group:
        name: '{{ ood_apps_admin_group }}'
        gid: '150'
        system: 'yes'

