---

- name: Download and link trinity apps
  ansible.builtin.include_tasks:
    file: trinity.yml

- name: Run apps tasks
  ansible.builtin.include_tasks:
    file: "app.yml"
    
  loop: "{{ ood_apps }}"
  loop_control:
    loop_var: app
