---
- name: Restart prometheus_node_exporter
  listen: "restart prometheus_node_exporter"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus_node_exporter
    state: restarted
  when:
    - not ansible_check_mode
