---
- name: Create the prometheus_infiniband_exporter group
  group:
    name: "{{ prometheus_infiniband_exporter_system_group }}"
    state: present
    system: true
  when: prometheus_infiniband_exporter_system_group != "root"

- name: Create the prometheus_infiniband_exporter user
  user:
    name: "{{ prometheus_infiniband_exporter_system_user }}"
    group: "{{ prometheus_infiniband_exporter_system_group }}"
    groups: "{{ prometheus_infiniband_exporter_additional_system_groups }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
  when: prometheus_infiniband_exporter_system_user != "root"

- name: Create prometheus_infiniband_exporter_binary_install_dir
  file:
    path: "{{prometheus_infiniband_exporter_binary_install_dir}}"
    state: directory
    mode: 0755

- name: Create the infinibandtool {{_prometheus_infiniband_exporter_tmp_dir}} if not exists
  file:
    path: "{{_prometheus_infiniband_exporter_tmp_dir}}"
    state: directory
    mode: 0755

- name: Create log dir if prometheus_infiniband_exporter_log_dir is defined
  ansible.builtin.file:
    path: "{{ prometheus_infiniband_exporter_log_dir }}"
    state: directory
    mode: 0755
  when:
    - prometheus_infiniband_exporter_log_dir is defined

- name: "Download prometheus-infiniband-exporter binary from {{prometheus_infiniband_exporter_binary_url}} to local folder"
  get_url:
    url: "{{ prometheus_infiniband_exporter_binary_url }}"
    dest: "{{prometheus_infiniband_exporter_binary_install_dir}}/prometheus-infiniband-exporter"
    mode: 0755
  register: _download_archive
  until: _download_archive is succeeded
  retries: 6
  delay: 20

- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version}}.yaml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version}}.yaml"
  ignore_errors: true

- name: Install prometheus_infiniband_exporter_packages packages
  package:
    name: "{{ prometheus_infiniband_exporter_packages }}"
    state: present
  when: prometheus_infiniband_exporter_packages is defined

