---
# vars file for ood-portal

ood_repository_rpms:
  - name: epel-release
  - name: "https://yum.osc.edu/ondemand/3.1/ondemand-release-web-3.1-1.el{{ansible_distribution_major_version}}.noarch.rpm"
    no_gpgcheck: True

ood_packages:
  - luna2-python
  - ondemand

ood_dex_packages:
  - ondemand-dex

ood_pam_packages:
  - mod_authnz_pam

# 'pam' or 'dex' ( only openldap is configured for dex )
ood_auth_provider: 'dex' 

ood_download_url: "https://updates.clustervision.com/trinityx/{{ trix_version }}/luna2/noarch/pip/{{ trix_stream }}/ood/trinityx-ood-2.0.latest.tar.gz"

ood_cluster_name: TrinityX
ood_login_host: "controller.cluster"
ood_ldap_host: "10.141.255.254"
ood_enable_ssl: true


ood_admin_group: admins

ood_port: 8080
ood_version: '3.0'
ood_user: 'apache'
ood_cfg_path: /etc/ood/config/
ood_brand: TrinityX
ood_vnc_idle_timeout: 180
ood_vnc_desktop: xfce

ood_custom_apps:
  - bmcsetup
  - cluster
  - group
  - network
  - node
  - osimage
  - otherdev
  - secrets
  - service
  - switch
  - control
  - users
  - osimagetag
  - monitor
  - dns
  - slurm
  - infiniband
  - rack

ood_admin_apps:
  - bmcsetup
  - cluster
  - group
  - network
  - node
  - osimage
  - otherdev
  - secrets
  - service
  - switch
  - control
  - users
  - osimagetag
  - monitor
  - dns
  - slurm
  - infiniband
  - rack

ood_user_apps: []
