---
# handler file for luna

- name: restart xinetd
  service:
    name: xinetd
    state: restarted

- name: restart dhcpd
  service:
    name: dhcpd
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart named
  service:
    name: named
    state: restarted

- name: restart luna2-daemon
  service:
    name: luna2-daemon
    state: restarted

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
  notify: fix firewall zones

- name: fix firewall zones
  shell: /tmp/fix-firewalld-zones.sh
  ignore_errors: true

