---

image_core_packages:                                                                                                                                                                         
  - "epel-release"
  - "kernel"
  - "grub2"
  - "grub2-tools"
  - "grub2-efi-x64"
  - "grub2-efi-x64-modules"
  - "tzdata"
  - "bind-utils"
  - "shim-x64"
  - "efibootmgr"
  - "dosfstools"
  - "lvm2"
  - "mdadm"
  - "lbzip2"
  - "aria2"
  - "tpm2-tools"
  - "dmidecode"
  - "luna2-client"
  - "selinux-policy"
  - "elfutils-libs"

luna2_noarch_repo_package: "https://updates.clustervision.com/trinityx/{{ trix_version }}/luna2/noarch/rpms"

