---
- name: Create Base
  ansible.builtin.include_tasks:
    file: base.yaml
  when: not base-plus-only

- name: Create Base-Plus
  ansible.builtin.include_tasks:
    file: base-plus.yaml

- name: Refresh the list of hosts in the inventory
  meta: refresh_inventory
