---
- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yaml"
  ignore_errors: true

- name: Get image path
  set_fact:
    image_path: "{{ trix_images }}/{{ image_name }}"

- name: Create dir for compute image
  file:
    name: "{{ image_path }}"
    state: directory

- name: Create Base
  ansible.builtin.include_tasks:
    file: base.yaml
  when: not base-plus-only

- name: Create Base-Plus
  ansible.builtin.include_tasks:
    file: base-plus.yaml

- name: Refresh the list of hosts in the inventory
  meta: refresh_inventory
