stages:
  - rollout

Matrix:
  stage: rollout
  # image: alpine:latest
  parallel:
    matrix:
    - TAG: "rocky8"
    - TAG: "rocky9"
    - TAG: "centos8"
    - TAG: "centos9"
    - TAG: "rhel8"
    - TAG: "rhel9"
    - TAG: "alma8"
    - TAG: "alma9"
  tags:
  - $TAG
  - "vm"
  script:
  - cat /etc/os-release
  - ls

