---
# Main file to enable the Azure Support for the TrinityX Installation.

- block:
  - name: Install Microsoft Azure CLI on Redhat
    include_tasks: "{{ role_path }}/tasks/redhat-azure-cli.yml"
    when:
      - ansible_facts['os_family'] == "RedHat"

  - name: Install Microsoft Azure CLI on Debian
    include_tasks: "{{ role_path }}/tasks/debian-azure-cli.yml"
    when:
      - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  when:
    - vars.azure_installer == 'azure-cli'

- block:
  - name: Create GRUB VHD Disk
    include_tasks: "{{ role_path }}/tasks/redhat-vhd.yml"
    when:
      - ansible_facts['os_family'] == "RedHat"

  - name: Create GRUB VHD Disk
    include_tasks: "{{ role_path }}/tasks/debian-vhd.yml"
    when:
      - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- block:
  - name: Verifying terraform files directory exists
    file:
      path: "{{ terraform_files }}"
      state: directory

  - name: Generate terraform.tfvars file
    template:
      src: terraform.tfvars.j2
      dest: "{{ terraform_files }}/terraform.tfvars"
  when:
    - vars.azure_installer == 'terraform'
