---
# Enable the Azure Support with Terraform for the TrinityX Installation.

- name: Check if Terraform is already Installed
  shell: "terraform -h"
  register: terraform_check
  ignore_errors: true

- name: Install Terraform Dependency
  yum:
    disable_gpg_check: true
    name: "yum-utils"
    state: present
  when: terraform_check.stderr

- name: Add Terraform Repository
  shell: "yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
  when: terraform_check.stderr

- name: Install Terraform
  yum:
    disable_gpg_check: true
    name: "terraform"
    state: present
  when: terraform_check.stderr
