---
galaxy_info:
  author: Will Szumski
  role_name: stackhpc.prometheus-slurm-exporter
  description: Prometheus Slurm Exporter
  license: MIT
  company: StackHPC
  min_ansible_version: 2.6
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: Debian
      versions:
        - stretch
        - buster
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 30
  galaxy_tags:
    - monitoring
    - prometheus
    - exporter
    - metrics
    - system

dependencies: []
