---

vpn_remote_public_ip:
vpn_local_external_ip:

vpn_local_private_subnet:
vpn_remote_private_subnet:

vpn_psk_secret: D8KgB2SQHZ+zsE/fxlmX+I9m2P4zkCRCib9Jw9vEO14=
vpn_esp_proposal: aes256-sha1-modp1024
