---

- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version}}.yaml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version}}.yaml"
  ignore_errors: true

- name: Install rdma packages
  yum:
    name: '{{ rdma_packages }}'
    state: present
  tags: install-only
  retries: "{{ network_retries | default(3) }}"
  delay: "{{ network_delay | default(15) }}"

# - name: Enable rdma services
#  service:
#    name: '{{ item }}'
#    state: started
#    enabled: true
#  with_items:
#    - rdma
#    - rdma-ndd

- name: Enable rdma services
  systemd:
    name: '{{ item }}'
    enabled: true
  with_items:
    - rdma-ndd

- name: Start rdma services
  systemd:
    name: '{{ item }}'
    state: started
  with_items:
    - rdma-ndd
  when: ansible_connection not in 'chroot'

# below is commonly done when IB is used in this context
#- name: Place i40iw blacklist
#  template:
#    src: i40.conf.j2
#    dest: /etc/modprobe.d/i40.conf
