---
# Main file to enable the AWS Cloud Support for the TrinityX Installation.

- block:
  - name: Install HashiCorp Terraform on Redhat
    include_tasks: "{{ role_path }}/tasks/redhat-terraform.yml"
    when:
      - ansible_facts['os_family'] == "RedHat"

  - name: Install HashiCorp Terraform on Debian
    include_tasks: "{{ role_path }}/tasks/debian-terraform.yml"
    when:
      - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  when:
    - vars.azure_installer == 'terraform'

- block:
  - name: Install Amazon Web services CLI on Redhat
    include_tasks: "{{ role_path }}/tasks/aws.yml"
  when:
    - vars.azure_installer == 'aws'
