---
- name: Run role
  hosts: all
  any_errors_fatal: true
  roles:
    - ansible-slurm-exporter
  vars:
    prometheus_slurm_exporter_system_group: "root"
    prometheus_slurm_exporter_system_user: "root"
