---
- name: Copy amtool config
  ansible.builtin.template:
    force: true
    src: "{{ prometheus_alertmanager_amtool_config_file }}"
    dest: "{{ _prometheus_alertmanager_amtool_config_dir }}/config.yml"
    owner: alertmanager
    group: alertmanager
    mode: 0644

- name: Copy alertmanager config
  ansible.builtin.template:
    force: true
    src: "{{ prometheus_alertmanager_config_file }}"
    dest: "{{ prometheus_alertmanager_config_dir }}/prometheus_alertmanager.yml"
    owner: alertmanager
    group: alertmanager
    mode: 0644
    validate: "{{ _prometheus_alertmanager_binary_install_dir }}/amtool check-config %s"
  notify:
    - restart alertmanager

- name: Copy alertmanager web config ( for basic auth )
  ansible.builtin.template:
    force: true
    src: "{{ prometheus_alertmanager_config_file }}"
    dest: "{{ prometheus_alertmanager_config_dir }}/alertmanage.web.yml"
    owner: alertmanager
    group: alertmanager
    mode: 0644
    # validate: "{{ _prometheus_alertmanager_binary_install_dir }}/amtool check-config %s"
  notify:
    - restart alertmanager
  when: prometheus_alertmanager_auth_user is defined

- name: Create systemd service unit
  ansible.builtin.template:
    src: prometheus_alertmanager.service.j2
    dest: /etc/systemd/system/prometheus_alertmanager.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart alertmanager

- name: Copy alertmanager template files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prometheus_alertmanager_config_dir }}/templates/"
    force: true
    owner: alertmanager
    group: alertmanager
    mode: 0644
  with_fileglob: "{{ prometheus_alertmanager_template_files }}"
  notify:
    - restart alertmanager
