---
- name: Install selinux python packages [RedHat]
  ansible.builtin.package:
    name: "{{ ['libselinux-python', 'policycoreutils-python']
           if ansible_python_version is version('3', '<') else
           ['python3-libselinux', 'python3-policycoreutils'] }}"
    state: present
  register: _install_selinux_packages
  until: _install_selinux_packages is success
  retries: 10
  delay: 15
  when: ansible_os_family | lower == "redhat"

- name: Install selinux python packages [clearlinux]
  ansible.builtin.package:
    name: sysadmin-basic
    state: present
  register: _install_selinux_packages
  until: _install_selinux_packages is success
  retries: 10
  delay: 15
  when:
    - ansible_distribution | lower == "clearlinux"
