---
- name: Reload and restart prometheus-alertmanager
  listen: "restart"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus-alertmanager
    state: restarted

- name: Reload prometheus-alertmanager
  listen: "reload"
  become: true
  ansible.builtin.systemd:
    name: prometheus-alertmanager
    state: reloaded
