---


# simple check to see if we have group_vars/all.yml (forward) compatibility

vhd_name: 'azure'
vhd_core_packages:
  - "@core"
  - "kernel"
  - "grub2"
  - "grub2-efi"
  - "grub2-efi-x64"
  - "grub2-efi-x64-modules"
  - "grub2-efi-x64-modules"
  - "efibootmgr"
  - "bind-utils"
  - "shim-x64"
  - "edk2-ovmf"
  - "lvm2.x86_64"

on_premise_controller_ip: 10.141.255.254
include_ipxe_efi_build: false

