---

- name: Get image path
  set_fact:
    image_path: "{{ trix_images }}/{{ image_name }}"

- name: Downloading base image
  get_url:
    url: "{{ base_image_repo }}/base-image-{{ base_image_distribution }}.tgz"
    dest: "/trinity/extra/base-image-{{ base_image_distribution }}.tgz"

- name: Create dir for compute image
  file:
    name: "{{ image_path }}"
    state: directory

- name: Extracting base image
  unarchive:
    src: "/trinity/extra/base-image-{{ base_image_distribution }}.tgz"
    dest: "{{ image_path }}"

