---

- name: Get image path
  set_fact:
    image_path: "{{ trix_images }}/{{ image_name }}"

- name: Verifying if dir for compute image exists
  stat:
    path: "{{ image_path }}"
  register: image_dir_check

- block:
  - name: Create temporary dir for downloading base image
    file:
      name: "{{ trix_root }}/downloads"
      state: directory

  - name: Downloading base image
    get_url:
      url: "{{ image_download_repo }}/base-image-{{ image_download_distribution }}.tgz"
      dest: "{{ trix_root }}/downloads/base-image-{{ image_download_distribution }}.tgz"

  - name: Create dir for compute image
    file:
      name: "{{ image_path }}"
      state: directory

  - name: Extracting base image
    unarchive:
      src: "{{ trix_root }}/downloads/base-image-{{ image_download_distribution }}.tgz"
      dest: "{{ image_path }}"
  when: not image_dir_check.stat.exists
