---

- name: Ensure lvm can be controlled from pacemaker by adding empty volume in lvm activation
  lineinfile:
    dest: "/etc/lvm/lvm.conf"
    insertafter: '^activation {'
    line: "	volume_list = [ ]"
  ignore_errors: true

- name: Create empty DRBD disk list
  set_fact:
      drbd_fs_disks: []

- name: Build DRBD disk list
  set_fact:
      drbd_fs_disks:
        '{{ drbd_fs_disks +
          [{ "name": item.name,
             "disk": item.disk,
             "fstype": item.fstype | default(""),
             "options": item.options | default(""),
             "mount": item.mount | default(False),
             "device": item.device }] }}'
  with_items: "{{ shared_fs_disks }}"
  when: item.type == 'drbd'

- debug:
    msg: "{{ drbd_fs_disks }}"

- name: Configure DRBD
  ansible.builtin.include_tasks:
    file: drbd.yaml
  when: drbd_fs_disks is defined and drbd_fs_disks|length > 0

# more types can be added here
# ....

- name: Configure Partitions
  ansible.builtin.include_tasks:
    file: partitions.yaml
  when: shared_fs_partitions is defined

# wrapping things up

- block:
  - name: Clear possible pacemaker dependency messages
    shell: "pcs resource cleanup"

  - name: Wait 10s for cleanup to take effect
    wait_for:
      timeout: 10

  - name: Clear possible pacemaker dependency messages
    shell: "pcs resource cleanup"
  when: primary
