---

- name: Create empty DRBD disk list
  set_fact:
      drbd_fs_disks: []

- name: Build DRBD disk list
  set_fact:
      drbd_fs_disks:
        '{{ drbd_fs_disks +
          [{ "name": item.name,
             "disk": item.disk,
             "fstype": item.fstype | default(""),
             "options": item.options | default(""),
             "mount": item.mount | default(False),
             "device": item.device }] }}'
  with_items: "{{ shared_fs_disks }}"
  when: item.type == 'drbd'

- debug:
    msg: "{{ drbd_fs_disks }}"

- name: Configure DRBD
  ansible.builtin.include_tasks:
    file: drbd.yaml
  when: drbd_fs_disks is defined and drbd_fs_disks|length > 0

