---

- debug:
    msg: "{{ shared_fs_partitions }}"

- name: Check if disk is already mounted
  shell: '/usr/bin/mount | grep " {{ item.name }} "'
  register: shared_fs_partitions_mounted
  changed_when: false
  failed_when: false
  loop: "{{ shared_fs_partitions }}"

- name: Check if lv disk already exists
  shell: '/usr/sbin/lvs | grep "{{ item.name | replace("/","_") }}"'
  register: shared_fs_partitions_lvs
  changed_when: false
  failed_when: false
  loop: "{{ shared_fs_partitions }}"

- name: Check if zfs disk already exists
  shell: '/usr/sbin/zfs | grep "{{ item.name | replace("/","_") }}"'
  register: shared_fs_partitions_zfs
  changed_when: false
  failed_when: false
  loop: "{{ shared_fs_partitions }}"

- name: Ensuring temporary mount location exists
  file:
    path: /mnt
    owner: root
    group: root
    state: directory

- block:
  - name: Create a fake fstab for the next step
    tempfile:
      path: /tmp
      prefix: fstab.
      state: file
    register: shared_fs_partitions_fake_fstab

  # ------------------------------------------

# lvcreate --addtag pacemaker -l 100%FREE -n Newlvvdb newvdb --config 'activation { volume_list = [ "@pacemaker" ] } 

  - name: Creating the Logical Volume
    shell: >
      lvcreate --addtag pacemaker -L {{ item.item['size'] }}
      --wipesignatures y --yes --zero y
      -n {{ item.item['name'] | replace("/","_") }} 
      {{ item.item['vgroup'] }} --config 'activation { volume_list = [ "@pacemaker" ] }'
    loop: "{{ shared_fs_partitions_lvs.results }}"
    ignore_errors: yes
    when: 
      - item.rc != 0
      - item.item['vgroup'] is defined

  - name: Creating the ZFS Volume
    shell: >
      zfs create {{ item.item['zpool'] }}/{{ item.item['name'] | replace("/","_") }} 
      {{ item.item['options']|default('') }} 
    loop: "{{ shared_fs_partitions_zfs.results }}"
    ignore_errors: yes
    when: 
      - item.rc != 0
      - item.item['zpool'] is defined

  - name: Setting temporary mountlocation for ZFS Volume
    shell: >
      zfs set mountpoint=/mnt/{{ item.item['name'] | replace("/","_") }}-temp 
      {{ item.item['zpool'] }}/{{ item.item['name'] | replace("/","_") }}
    loop: "{{ shared_fs_partitions_zfs.results }}"
    ignore_errors: yes
    when: 
      - item.rc != 0
      - item.item['zpool'] is defined


# mkfs -t ext4 -m 1 -v /dev/yournewvg/lv_yournewlv

#  - name: Creating the partition
#    filesystem:
#      fstype: "{{ item.item['fstype'] }}"
#      dev: '/dev/{{ item.item["vgroup"] }}/{{ item.item["name"] | replace("/","_") }}'
#      force: yes
#      opts: "{{ item.item['options'] | default('') }}"
#    ignore_errors: yes
#    loop: "{{ shared_fs_partitions_mounted.results }}"
#    when: 
#      - item.rc != 0
#      - item.item['vgroup'] is not defined

  - name: Creating a file system on LV partition
    filesystem:
      fstype: "{{ item.item['fstype'] }}"
      dev: '/dev/{{ item.item["vgroup"] }}/{{ item.item["name"] | replace("/","_") }}'
      force: yes
      opts: "{{ item.item['options'] | default('') }}"
    ignore_errors: yes
    loop: "{{ shared_fs_partitions_mounted.results }}"
    when: 
      - item.rc != 0
      - item.item['vgroup'] is defined
      - item.item['fstype'] is defined

  - name: Temporarily mount the LV disks
    mount:
      src: '/dev/{{ item.item["vgroup"] }}/{{ item.item["name"] | replace("/","_") }}'
      path: '/mnt/{{ item.item["name"] | replace("/","_") }}-temp'
      fstype: "{{ item.item['fstype'] }}"
      state: mounted
      fstab: "{{ shared_fs_partitions_fake_fstab.path }}"
    loop: "{{ shared_fs_partitions_mounted.results }}"
    when: 
      - item.rc != 0
      - item.item['fstype'] is defined
      - item.item['vgroup'] is defined

  - name: Temporarily mount the ZFS disks
    #shell: "zpool import -o cachefile=none {{ item.item['zpool'] }}"
    shell: >
      zfs mount {{ item.item['zpool'] }}/{{ item.item['name'] | replace("/","_") }}
    loop: "{{ shared_fs_partitions_mounted.results }}"
    when: 
      - item.rc != 0
      - item.item['zpool'] is defined
    ignore_errors: true

  - name: Ensuring source location exists
    file:
      path: '{{ item.item["name"] }}'
      owner: root
      group: root
      state: directory
    loop: "{{ shared_fs_partitions_mounted.results }}"
    when: item.rc != 0

  - name: Wait 10s for mounts to settle
    wait_for:
      timeout: 10

  - name: Copy contents from local drives to shared resource
    synchronize:
      src: '{{ item.item["name"] }}/'
      dest: '/mnt/{{ item.item["name"] | replace("/","_") }}-temp/'
    loop: "{{ shared_fs_partitions_mounted.results }}"
    when: item.rc != 0

  - name: Temporarily umount the disks
    mount:
      path: '/mnt/{{ item.item["name"] | replace("/","_") }}-temp'
      state: unmounted
    loop: "{{ shared_fs_partitions_mounted.results }}"
    when: 
      - item.rc != 0
      - item.item['zpool'] is not defined

  - name: Setting the mountlocation for ZFS Volume
    shell: >
      zfs set mountpoint={{ item.item['name'] }} {{ item.item['zpool'] }}/{{ item.item['name'] | replace("/","_") }}
    loop: "{{ shared_fs_partitions_zfs.results }}"
    ignore_errors: yes
    when: 
      - item.rc != 0
      - item.item['zpool'] is defined

  # ------------------------------------------

  - name: Add pacemaker resource trinity-fs
    pcs_resource:
      name: 'trinity-fs-{{ item.name | replace("/","_") }}'
      resource_class: ocf
      resource_type: Filesystem
#      options: 'device=/dev/drbd/by-res/{{ item.name | replace("/","_") }}
      options: 'device=/dev/{{ item["vgroup"] }}/{{ item["name"] | replace("/","_") }}
          directory="{{ item.name }}" fstype={{ item.fstype }} 
          run_fsck=force force_unmount=safe op monitor interval=31s op
          monitor interval=67s OCF_CHECK_LEVEL=10 --group=Trinity-lvm-{{ item.name | replace("/","_") }}'
      state: present
    loop: "{{ shared_fs_partitions }}"
    when:
      - item['vgroup'] is defined

  - name: Add pacemaker colocation constraint - Trinity-fs with Trinity
    pcs_constraint_colocation:
      resource1: 'Trinity-lvm-{{ item.name | replace("/","_") }}'
      resource2: 'trinity-fs-{{ item.name | replace("/","_") }}'
      state: present
    loop: "{{ shared_fs_partitions }}"
    when:
      - item['vgroup'] is defined

  when: 
    - primary | default(False)
    - shared_fs_partitions_mounted is defined


