---
- name: Reload and restart prometheus-lshw-exporter
  listen: "restart prometheus-lshw-exporter"
  become: true
  systemd:
    daemon_reload: true
    name: prometheus-lshw-exporter
    state: restarted
  when: ansible_connection not in 'chroot'
