- name: Configure controller for VNC Server
  when: ansible_connection not in 'chroot'
  block:

  - name: Render vnc interactive app form.yml
    template:
      src: 'vnc/form.yml.j2'
      dest: '{{ ood_interactive_apps_path }}/bc_desktop/form.yml'
      mode: 0644
      owner: root
      group: root
      backup: "yes"
    when: "'vnc' in ood_interactive_apps"
    notify: run update_ood

  - name: Remove vnc interactive app form.yml if not app is not enabled
    file:
      path: '{{ ood_interactive_apps_path }}/bc_desktop/form.yml'
      state: absent
    when: "'vnc' not in ood_interactive_apps"
    notify: run update_ood
  
  # This should be done by controller because /trinity/shared is not mounted on compute node
  - name: Render ood-vnc-module template file
    template:
      src: 'vnc/module.lua.j2'
      dest: '{{ trix_shared }}/modulefiles/ood-vnc.lua'
      mode: '0644'
      owner: root
      group: root

# tasks file for ood-vnc
- name: Install ood-vnc requirements ( on machine whoose desktop is forwarded )
  block:
    - name: Install required yum repos
      dnf:
        name: "{{ item.name }}"
        state: present
        update_cache: true
        disable_gpg_check: "{{ item.no_gpgcheck | default(False) }}"
        enablerepo: "{{ item.enablerepo | default('') }}"
      with_items: "{{ ood_interactive_apps_vnc_repos_rpms }}"
      retries: "{{ rpm_retries | default(3) }}"
      delay: "{{ rpm_delay | default(15) }}"

    - name: Install required yum packages
      dnf:
        name: "{{ item.name }}"
        state: present
        update_cache: true
        disable_gpg_check: "{{ item.no_gpgcheck | default(False) }}"
        enablerepo: "{{ item.enablerepo | default('') }}"
      with_items: "{{ ood_interactive_apps_vnc_rpms }}"
      retries: "{{ rpm_retries | default(3) }}"
      delay: "{{ rpm_delay | default(15) }}"

