---
- import_playbook: trinity-redhat-image-create.yml
  vars:
    image_name: compute
    # The password to set up for the root user in the image.
    # If empty, it will be generated at random.
    #
    image_password:


- import_playbook: trinity-redhat-image-setup.yml
  vars:
    hostlist: "{{ image_name|default('compute') }}.osimages.luna"

- hosts:
    - "{{ image_name|default('compute') }}.osimages.luna"
  roles:
    - role: trinity/wrapup-images
      tags: wrapup-images


- hosts: controllers
  roles:
    - role: trinity/pack-images
      vars:
         params:
            image_name: "{{ image_name|default('compute') }}"
      tags: pack-images
