---
- hosts: localhost
  pre_tasks:
  #
  # the image name can be set in the below fact.
  #
  - name: Set image name
    set_fact:
      image_name: "login"
    tags: always

  - name: Verify if luna secret vault exists
    stat:
      path: "/trinity/local/etc/ssl/secret.key"
    register: stat_secret_key
    tags: always

  - block:
    - name: Import luna secret key
      slurp:
        src: "/trinity/local/etc/ssl/secret.key"
      register: luna_secret_key_b64

    - name: Set Luna secret key
      set_fact:
        luna_secret_key: "{{ luna_secret_key_b64['content'] | b64decode }}"
    when: stat_secret_key.stat.exists
    tags: always


- import_playbook: imports/trinity-redhat-image-create.yml
  vars:
    image_name: "{{ hostvars['localhost']['image_name'] }}"
    # The password to set up for the root user in the image.
    # If empty, it will be generated at random.
    #
    image_password:
    #
    # Alternative distribution build. Supported are Rocky + Centos, version 8, 9, 8.9, 9.3
    # or any docker image, e.g. rockylinux:8
    #alternative_distribution: Rocky-9.3
    # 
    # The alternative source can be 'base' or 'docker'
    #alternative_image_source: 'base'

- import_playbook: imports/trinity-redhat-login-setup.yml
  vars:
    hostlist: "{{ hostvars['localhost']['image_name'] }}.osimages.luna"
    in_login_image: true
    luna_secret_key: "{{ hostvars['localhost']['luna_secret_key'] }}"

#- hosts:
#    - "{{ hostvars['localhost']['image_name'] }}.osimages.luna"
#  roles:
#    - role: trinity/slurm
#      slurm_conf_path: '{{ trix_shared }}/etc/slurm'
#      slurm_spool_path: '{{ trix_shared }}/var/spool/slurm'
#      munge_conf_path: '{{ trix_shared }}/etc/munge'
#      tags: slurm
#
#    - role: trinity/wrapup-images
#      tags: wrapup-images

- hosts: controllers
  roles:
    - role: trinity/pack-images
      vars:
         params:
            image_name: "{{ hostvars['localhost']['image_name'] }}"
      tags: pack-images
