---
# tasks file for Aria2c

- name: Stop prometheus_sd_luna service if running
  systemd:
    name: prometheus_sd_luna.service
    state: stopped
  ignore_errors: yes


- name: Copy prometheus_sd_luna script
  copy:
    src: "files/prometheus_sd_luna.py"
    dest: "{{ prometheus_sd_luna_script_path }}"
    owner: root
    group: root
    mode: 0755

- name: Add interpreter shebang to prometheus_sd_luna script
  lineinfile:
    path: "{{ prometheus_sd_luna_script_path }}"
    line: "#!{{ prometheus_sd_python_interpreter }}"
    insertbefore: BOF
    state: present
    create: yes

- name: Render prometheus_sd_luna service file
  template:
    src: "templates/prometheus_sd_luna.service.j2"
    dest: "/etc/systemd/system/prometheus_sd_luna.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd

- name: Enable prometheus_sd_luna service
  systemd:
    name: prometheus_sd_luna.service
    enabled: yes
    state: started
