---
- name: Reload and restart prometheus
  listen: "restart"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus-server
    state: restarted

- name: Reload prometheus
  listen: "reload"
  become: true
  ansible.builtin.systemd:
    name: prometheus-server
    state: reloaded
