---

#- include_tasks: controller.yml
#  when:
#    - ansible_connection not in 'chroot'
#    - not compute|default(False)

- block:
  
  - name: "Ensure alertX drainer alertx_drainer_daemon_path directory exists"
    file:
      path: "{{ alertx_drainer_daemon_path }}"
      state: directory
      owner: root
      group: root
      mode: '0755'
  
  - name: "Install drainer.py"
    copy:
      src: 'drainer.py'
      dest: '{{ alertx_drainer_daemon_path }}'
      owner: 'root'
      group: 'root'
      mode: '0750'

  - name: Install service file to systemd
    template:
      src: 'alertx-drainer.service.j2'
      dest: '/etc/systemd/system/alertx-drainer.service'
      owner: 'root'
      group: 'root'
      mode: '0644'
    notify: reload systemd daemon

  - name: Reload systemd to recognize new service
    ansible.builtin.command: systemctl daemon-reload

  - name: Enable alertx-drainer.service
    systemd:
      name: alertx-drainer.service
      enabled: yes

  - name: Start alertx-drainer.service
    systemd:
      name: alertx-drainer.service
      state: started


- block:
  - name: Render AlertX hook script
    template:
      src: 'alertx-hook.sh.j2'
      dest: '/usr/local/sbin/alertx-hook.sh'
      owner: root
      group: root
      mode: 0700
    
  - name: Render /etc/systemd/system/alertx-hook.service
    template:
      src: 'alertx-hook.systemd.j2'
      dest: '/etc/systemd/system/alertx-hook.service'
      owner: root
      group: root
      mode: 0644

  - name: Enable luna services
    service:
      name: 'alertx-hook.service'
      enabled: true
  when: ansible_connection in 'chroot' or compute|default(False)
