- name: Install ondemand-dex required packages
  package:
    name: "{{ item }}"
    state: "present"
  loop: "{{ ood_dex_packages }}"
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

- name: Enable ondemand-dex service on startup
  service:
    name: ondemand-dex
    enabled: "{{ ood_auth_provider == 'dex' }}"
    state: "{{ 'started' if ood_auth_provider == 'dex' else 'stopped'}}"
