---
- name: Install ondemand-dex required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ ood_dex_rpms }}"
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

- name: Enable ondemand-dex service on startup
  ansible.builtin.service:
    name: ondemand-dex
    enabled: "{{ ood_auth_provider == 'dex' }}"
    state: "{{ 'started' if ood_auth_provider == 'dex' else 'stopped' }}"
