---
# Enable the GCP CLI Support for the TrinityX Installation.

- name: Check if gcloud is already Installed
  shell: "gcloud version"
  register: gcloud_check
  ignore_errors: true

- name: Update DNF with gcloud CLI repository information
  shell: |
    tee -a /etc/yum.repos.d/google-cloud-sdk.repo << EOM
    [google-cloud-cli]
    name=Google Cloud CLI
    baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64
    enabled=1
    gpgcheck=1
    repo_gpgcheck=0
    gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    EOM
  when: gcloud_check.stderr

- name: Install the gcloud CLI
  dnf:
    disable_gpg_check: true
    name: "google-cloud-cli"
    state: present
  when: gcloud_check.stderr


