- name: Create credentials folder if it does not exist
  file:
    path: "{{ prometheus_auth_credentials_file | dirname }}"
    state: directory
    mode: 0755

- name: Retrieve password from {{ prometheus_auth_credentials_file }} if exists, generate it otherwise
  set_fact:
    prometheus_auth_password: "{{ lookup('password',
                        prometheus_auth_credentials_file,
                        chars=['ascii_letters','digits','hexdigits']) }}"


