---
- name: Copy the Slurm Exporter systemd service file
  template:
    src: prometheus_slurm_exporter.service.j2
    dest: /etc/systemd/system/prometheus_slurm_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus_slurm_exporter

- name: Allow Slurm Exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ prometheus_slurm_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"

- name: Configure prometheus slurm-exporter if prometheus_slurm_exporter_sd_file is defined
  blockinfile:
    path: "{{ prometheus_slurm_exporter_sd_file }}"
    block: |
      - targets:
        - localhost:{{ prometheus_slurm_exporter_web_listen_port }}
        labels:
          exporter: slurm
    marker: "### {mark} ANSIBLE MANAGED BLOCK (controller.slurm_exporter)"
  when:
    - prometheus_slurm_exporter_sd_file is defined