---
- name: Copy the Slurm Exporter systemd service file
  template:
    src: slurm_exporter.service.j2
    dest: /etc/systemd/system/slurm_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart slurm_exporter

- name: Allow Slurm Exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ slurm_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
