---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - prometheus-slurm-exporter-install
    - prometheus-slurm-exporter-configure
    - prometheus-slurm-exporter-run

- import_tasks: preflight.yml
  tags:
    - prometheus-slurm-exporter-install
    - prometheus-slurm-exporter-configure
    - prometheus-slurm-exporter-run

- import_tasks: install.yml
  become: true
  tags:
    - prometheus-slurm-exporter-install

- import_tasks: configure.yml
  become: true
  tags:
    - prometheus-slurm-exporter-configure

- name: Ensure Slurm Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: slurm_exporter
    enabled: true
    state: started
  tags:
    - prometheus-slurm-exporter-run
