---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - slurm_exporter_install
    - slurm_exporter_configure
    - slurm_exporter_run

- import_tasks: preflight.yml
  tags:
    - slurm_exporter_install
    - slurm_exporter_configure
    - slurm_exporter_run

- import_tasks: install.yml
  become: true
  when: (not __slurm_exporter_is_installed.stat.exists) or (__slurm_exporter_current_version.content != slurm_exporter_version)
  tags:
    - slurm_exporter_install

- import_tasks: configure.yml
  become: true
  tags:
    - slurm_exporter_configure

- name: Ensure Slurm Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: slurm_exporter
    enabled: true
    state: started
  tags:
    - slurm_exporter_run
