---
# handler file for slurm

- name: restart slurm
  service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - slurmdbd
    - slurmctld
  retries: 10
  delay: 15
  when: primary|default(True)

- name: restart munge
  service:
    name: munge
    state: restarted
  retries: 10
  delay: 15
  when: primary|default(True)
