---
# Install additional packages and tunables

- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ package_arch }}/main.yaml"
    - "{{ package_arch }}/{{ ansible_distribution }}{{ ansible_distribution_major_version}}.yaml"
    - "{{ package_arch }}/{{ ansible_os_family }}{{ ansible_distribution_major_version}}.yaml"
  ignore_errors: true

- name: Install additional packages
  yum:
    name: "{{ install_packages }}"
    state: present
    enablerepo: 
      - powertools
      - crb
    disable_gpg_check: true
  tags: install-only
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

- name: Enable haveged service
  service:
    name: haveged
    enabled: true

- name: Start haveged service
  service:
    name: haveged
    state: started
  when: not in_image
