---
# tasks file for rsyslog

- name: Install rsyslog
  yum:
    name: rsyslog
    state: installed
  when: ansible_facts['os_family'] == "RedHat"
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

- name: Install rsyslog
  apt:
    name: rsyslog
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Configure listeners
  blockinfile:
    path: '/etc/rsyslog.d/{{ item.proto | lower }}-listeners.conf'
    create: true
    owner: root
    group: root
    block: |
      $ModLoad im{{ item.proto | lower }}
      ${{ 'Input' if item.proto|lower == 'tcp' else '' }}{{ item.proto | upper }}ServerRun {{ item.port }}
  with_items: '{{ syslog_listeners }}'
  notify: restart rsyslog

- name: Create cluster-messages log directory
  file:
    path: /var/log/cluster-messages
    state: directory

- name: Add template rules
  template:
    src: 'template-rule.conf.j2'
    dest: '/etc/rsyslog.d/template-rule-{{ item.name }}.conf'
    owner: root
    group: root
  with_items: '{{ syslog_file_template_rules }}'
  notify: restart rsyslog

- name: Add forwarding rules
  template:
    src: 'forwarding.conf.j2'
    dest: '/etc/rsyslog.d/forwarding-{{ item.name }}.conf'
    owner: root
    group: root
  with_items: '{{ syslog_forwarding_rules }}'
  notify: restart rsyslog

- name: Add SELinux rules for the forwarding ports
  seport:
    ports: '{{ item.port }}'
    proto: '{{ item.proto }}'
    setype: syslogd_port_t
    state: present
  with_items: '{{ syslog_forwarding_rules }}'
  when: enable_selinux|default(True)
  ignore_errors: true

- name: Enable rsyslog service
  systemd:
    name: rsyslog
    enabled: true

- name: Start rsyslog daemon
  service:
    name: rsyslog
    state: started
  when: ansible_connection not in 'chroot'
