---
# tasks file for pbspro

- name: Configure OpenHPC repos
  ansible.builtin.yum_repository:
    name: "openhpc-{{ item.name }}"
    description: "openhpc-{{ item.name }}"
    baseurl: "{{ item.repo }}"
    gpgcheck: "{{ item.gpgcheck | default(False) }}"
    gpgkey: "{{ item.gpgkey | default('') }}"
  with_items: "{{ lookup('ansible.builtin.vars', 'el' + ansible_distribution_major_version + '_openhpc_repositories') }}"

- name: Install Openpbs-server
  yum:
    name: openpbs-server-ohpc
    state: present
  tags: install-only
  when: on_controller|default(True)
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

- name: Install openpbs-execution-ohpc
  yum:
    name: openpbs-execution-ohpc
    state: present
  tags: install-only
  when: on_node|default(False)
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

- name: Configure PBSPro
  template:
    src: pbs.conf.j2
    dest: /etc/pbs.conf
  notify: restart pbs

- name: Configure mom_priv
  template:
    src: mom_priv_config.j2
    dest: /var/spool/pbs/mom_priv/config
  notify: restart pbs
  when: on_node|default(False)

- name: Enable and start PBS
  systemd:
    name: pbs
    enabled: "yes"
    state: started
