---
# Install support script and configure bash environment

- name: Install needed packages
  yum:
    name: '{{ cv_support_packages }}'
    state: present
  tags: install-only
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

- name: Install needed pip packages
  pip:
    name: '{{ cv_support_pip_packages }}'
    executable: pip3
  tags: install-only

- name: Render /root/.bash_profile
  template:
    src: bash_profile.j2
    dest: /root/.bash_profile

- name: Add releaseversion to the controllers
  lineinfile:
    path: '/etc/trinityx-release'
    line: "{{ trix_version }}"
    state: present
    create: 'yes'
  when: primary|default(True)

- name: Add /trinity/site file to the controllers
  lineinfile:
    path: '/trinity/site'
    line: '{{ project_id }}'
    state: present
    create: 'yes'
  when: primary|default(True)

- name: Install diagnostics tools
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items: "{{ trix_tools }}"

- name: Configure remote-assistance tunnel service
  copy:
    src: "remote-assistance.service"
    dest: "/etc/systemd/system/remote-assistance.service"
  notify: reload systemd daemon

- name: Configure systemd service
  systemd:
    daemon_reload: "yes"
    name: "remote-assistance.service"

- name: Install MOTD
  template:
    src: "motd.j2"
    dest: /etc/motd
  when: primary|default(True)

- name: Copy examples
  copy:
    src: "examples/"
    dest: "{{ trix_examples }}"
