---
- name: Add dracut.conf.d entries
  template:
    src: trinity.conf.j2
    dest: "{{ image_path}}/etc/dracut.conf.d/trinity.conf"

# - name: Copy gpg keys
#  copy:
#    src: "/etc/pki/rpm-gpg"
#    dest: "{{ image_path }}/etc/pki/"

- name: Make .ssh root directory
  file:
    path: "{{ image_path }}/root/.ssh"
    mode: 0700
    owner: root
    group: root
    state: directory

- name: Ensure /etc/trinity/passwords/images/{{ image_name }} exists
  file:
    path: '/etc/trinity/passwords/images/{{ image_name }}'
    state: directory

- name: Store root password if defined
  template:
    src: root.txt
    dest: '/etc/trinity/passwords/images/{{ image_name }}/root.txt'
  when: image_password|default([])

- name: Generate SSH keys
  user:
    name: root
    generate_ssh_key: true
    ssh_key_file: "{{ image_path }}/root/.ssh/id_rsa"

- name: Add controller's key to authorized keys
  authorized_key:
    user: root
    state: present
    key: '{{ lookup("file", "/root/.ssh/id_rsa.pub") }}'
    path: "{{ image_path }}/root/.ssh/authorized_keys"

- name: Add cluster key to authorized keys
  authorized_key:
    user: root
    state: present
    key: '{{ lookup("file", "/root/.ssh/id_cluster_rsa.pub") }}'
    path: "{{ image_path }}/root/.ssh/authorized_keys"
  when: ha | default(False)

- name: Create node config directory
  file:
    path: '{{ image_path }}/{{ trix_luna }}/node/config/'
    state: directory

- name: Render node luna.ini
  template:
    src: 'luna2.ini.j2'
    dest: '{{ image_path }}/{{ trix_luna }}/node/config/luna.ini'
    owner: root
    group: root
    mode: 0640

- name: Verify if image already exists in luna
  shell: "luna osimage show {{ image_name }}"
  register: redhat_image_in_luna
  ignore_errors: true

- name: Creating image in luna
  shell: "luna osimage add -p \"{{ trix_images }}/{{ image_name }}\" -D {{ ansible_os_family|lower }} -R {{ ansible_distribution_major_version }} {{ image_name }}"
  when: redhat_image_in_luna is defined and redhat_image_in_luna.rc|int != 0

- name: Setting release for image
  shell: "luna osimage change -D {{ ansible_os_family|lower }} -R {{ ansible_distribution_major_version|lower }} {{ image_name }}"
  when: redhat_image_in_luna is defined and redhat_image_in_luna.rc|int == 0

- name: Kernel version in image
  shell: "ls {{ image_path }}/lib/modules|sort|tail -n1"
  register: kernel_version
  changed_when: false

- name: Set the kernel version for image
  ansible.builtin.shell:
    cmd: "luna osimage change -ver {{ kernel_version.stdout }} {{ image_name }}"

- name: Sync RHEL subscription and entitlements
  shell: "rsync --delete -arv /etc/pki/entitlement/ {{ image_path }}/etc/pki/entitlement/ && rsync --delete -arv /var/lib/rhsm/ {{ image_path }}/var/lib/rhsm/"
  when: ansible_distribution == "RedHat"
  ignore_errors: true

- name: Refresh the list of hosts in the inventory
  meta: refresh_inventory

