---

- name: Synchronizing /etc/trinity/passwords between controllers
  synchronize:
    src: /etc/trinity/passwords
    dest: /etc/trinity
    archive: true
    delete: true
  ignore_errors: true

- name: Refresh exportfs
  shell: "exportfs -a"
  ignore_errors: true

- name: Verify if interface and zone mismatch fix script exists
  stat:
    path: /tmp/fix-firewalld-zones.sh
  register: wrapup_fix_firewalld_zones_script

  # https://github.com/ansible-collections/ansible.posix/issues/75
- name: Run interface and zone mismatch fix script again...
  shell: '/tmp/fix-firewalld-zones.sh'
  ignore_errors: true
  when: wrapup_fix_firewalld_zones_script.stat.exists

- block:
  - name: set property 'standby' to 'absent' for non-primary node (unstandby)
    pcs_property:
      name: 'standby'
      node: '{{ ansible_hostname }}'
      state: 'absent'
    ignore_errors: true

  - name: Clear possible pacemaker dependency messages
    shell: "pcs resource cleanup"
    ignore_errors: true

  - name: Toggle pacemaker stonith property as non-primary is ready
    pcs_property:
      name: stonith-enabled
      value: '{{ fence_ipmilan_enabled }}'
  tags: ha,pcs,pacemaker,fencing
  when:
    - ha
    - not primary

- name: Set wrap-up flag
  copy:
    content: ""
    dest: /etc/trinity/controller.done
    force: false
