---

- name: Synchronizing /etc/trinity/passwords between controllers
  synchronize:
    src: /etc/trinity/passwords
    dest: /etc/trinity
    archive: true
    delete: true

- name: Refresh exportfs
  shell: "exportfs -a"
  ignore_errors: true

