---

- name: Synchronizing /etc/trinity/passwords between controllers
  synchronize:
    src: /etc/trinity/passwords
    dest: /etc/trinity
    archive: true
    delete: true

- name: Refresh exportfs
  shell: "exportfs -a"
  ignore_errors: true

- name: Verify if interface and zone mismatch fix script exists
  stat:
    path: /tmp/fix-firewalld-zones.sh
  register: wrapup_fix_firewalld_zones_script

  # https://github.com/ansible-collections/ansible.posix/issues/75
- name: Run interface and zone mismatch fix script again...
  shell: '/tmp/fix-firewalld-zones.sh'
  ignore_errors: true
  when: wrapup_fix_firewalld_zones_script.exists

