---
- name: Copy logrotate configuration files
  copy:
    src: '{{ item }}'
    dest: '/etc/logrotate.d/{{ item }}'
    force: "no"
  with_items:
    - trinityx
    - slurm
    - luna
    - aria2c
    - prometheus

- name: Changing owner and group for logrotate config
  file:
    path: '/etc/logrotate.d/{{ item }}'
    owner: root
    group: root
  with_items:
    - trinityx
    - slurm
    - luna
    - aria2c
    - prometheus


- name: Restart logrotate
  assert: {that: true, quiet: true}
  notify: restart logrotate
  changed_when: true
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version']|int > 8
