
- block:
  - name: Verify if luna secret vault exists
    stat:
      path: "{{ trix_ssl }}/secret.key"
    register: stat_secret_key

  - block:
    - name: Generate Luna Secret Key
      set_fact:
        luna_secret_key: "{{ lookup('password', '/dev/null length=32 chars=abcdef0123456789') }}"

    - name: Write luna secret key to vault
      copy:
        dest: "{{ trix_ssl }}/secret.key"
        content: "{{ luna_secret_key }}"
    when: not stat_secret_key.stat.exists

  - block:
    - name: Import luna secret key
      slurp:
        src: "{{ trix_ssl }}/secret.key"
      register: luna_secret_key_b64

    - name: Set Luna secret key
      set_fact:
        luna_secret_key: "{{ luna_secret_key_b64['content'] | b64decode }}"
    when: stat_secret_key.stat.exists


- block:
  - name: Verify if omapi vault exists
    stat:
      path: "{{ trix_ssl }}/omapi.key"
    register: stat_omapi_key

  - block:
    - name: Generate omapi Key
      set_fact:
        omapi_key: "{{ lookup('password', '/dev/null length=32 chars=abcdef0123456789') }}"

    - name: Write omapi key to vault
      copy:
        dest: "{{ trix_ssl }}/omapi.key"
        content: "{{ omapi_key }}"
    when: not stat_omapi_key.stat.exists

  - block:
    - name: Import omapi key
      slurp:
        src: "{{ trix_ssl }}/omapi.key"
      register: omapi_key_b64

    - name: Set omapi key
      set_fact:
        omapi_key: "{{ omapi_key_b64['content'] | b64decode }}"
    when: omapi_key.stat.exists


