---

required_packages:
  - "dnf-utils"
  - "distribution-gpg-keys"
                                                                                                                                                                                             
