go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
_prometheus_infiniband_exporter_repo: "prometheus-community/infiniband_exporter"
# Generate a temporary directory for prometheus with the current epoch
_prometheus_infiniband_exporter_tmp_dir: "/tmp/prometheus-infiniband-exporter"