---
- name: Get image path
  set_fact:
    image_path: "{{ trix_images }}/{{ image_name }}"

- name: Create dir for compute image
  file:
    name: "{{ image_path }}"
    state: directory

- name: Creating base image
  ansible.builtin.include_tasks:
    file: base.yml
  when: image_create_minimal|default(True)

- name: Extending base image
  ansible.builtin.include_tasks:
    file: base-plus.yml
  when: image_create_full|default(True)

- name: Refresh the list of hosts in the inventory
  meta: refresh_inventory
