---
- name: Copy the High Availability Exporter systemd service file
  template:
    src: prometheus-ha-exporter.service.j2
    dest: /etc/systemd/system/prometheus-ha-exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus-ha-exporter

- name: Allow High Availability Exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ prometheus_ha_exporter_web_listen_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"

- name: Configure prometheus ha-exporter if prometheus_ha_exporter_sd_file is defined
  blockinfile:
    path: "{{ prometheus_ha_exporter_sd_file }}"
    block: |
      - targets:
        - {{ ansible_fqdn }}:{{ prometheus_ha_exporter_web_listen_port }}
        labels:
          exporter: ha
      {% if ansible_hostname in (all_ctrl_hostnames|default([trix_ctrl_hostname])) %}
          luna_group: controller
      {% endif %}
    marker: "### {mark} ANSIBLE MANAGED BLOCK ({{ ansible_fqdn }}.prometheus_ha_exporter)"
  when:
    - prometheus_ha_exporter_sd_file is defined