- name: Install ondemand-dex required packages
  package:
    name: "{{ item }}"
    state: "present"
  loop: "{{ ood_portal_dex_packages }}"

- name: Enable ondemand-dex service on startup
  service:
    name: ondemand-dex
    enabled: "{{ ood_portal_auth_provider == 'dex' }}"
    state: "{{ 'started' if ood_portal_auth_provider == 'dex' else 'stopped'}}"
