---
# Enable the Azure Support with Terraform for the TrinityX Installation.

- name: Check if Terraform is already Installed
  shell: "terraform -h"
  register: terraform_check
  ignore_errors: true

- block:
  - name: Install Terraform Dependency
    yum:
      disable_gpg_check: true
      name: "yum-utils"
      state: present

  - name: Add Terraform Repository
    shell: "yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"

  - name: Install Terraform
    yum:
      disable_gpg_check: true
      name: "terraform"
      state: present
  when: terraform_check.rc|int != 0


#- name: Check if aws-cli is already Installed
#  shell: "aws help"
#  register: awscli_check
#  ignore_errors: true

- name: Remove the previous Installation
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/usr/local/bin/aws"
    - "/usr/local/bin/aws_completer"
    - "/usr/local/aws-cli"
    - "~/.aws/"
#  when: awscli_check.rc|int == 0

- name: Download the AWS installation file
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    force: true

- name: Unzip the installer
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/

- name: Installing AWS CLI
  shell: "sh /tmp/aws/install"

- name: Clean up
  file:
    state: absent
    path: /tmp/aws


