---
- name: Reload and restart prometheus-slurm-job-exporter
  listen: "restart prometheus-slurm-job-exporter"
  become: true
  systemd:
    daemon_reload: true
    name: prometheus-slurm-job-exporter
    state: restarted
  when: ansible_connection not in 'chroot'
