---
- name: Reload and restart prometheus-infiniband-exporter
  listen: "restart prometheus-infiniband-exporter"
  become: true
  systemd:
    daemon_reload: true
    name: prometheus-infiniband-exporter
    state: restarted
  when: not in_image
