---

- block:
  - name: Temporarily mount trinity/ha from controller1
    shell: "mount {{ trix_ctrl1_ip }}:{{ trix_ha }} {{ trix_ha }}"

  - name: Copy all secrets from ha storage
    copy:
      src: '{{ trix_ha }}/sync'
      dest: '{{ trix_local }}/'

  - name: Umount trinity/ha
    shell: "umount -l {{ trix_ha }}"
  when:
    - not primary

