---

- block:

  - name: Ensure temporary sync mount location exists
    file:
      path: /mnt/sync
      state: directory

  - name: Temporarily mount sync from controller1
    shell: "mount {{ trix_ctrl1_ip }}:{{ trix_sync }} /mnt/sync"

  - name: Copy all secrets
    copy:
      src: '/mnt/sync'
      dest: '{{ trix_sync }}'

  - name: Umount sync
    shell: "umount -l /mnt/sync"
  when:
    - not primary

