---

alertx_packages: []

alertx_noarch_pip_repository: "https://updates.clustervision.com/trinityx/{{ trix_version }}/alertx/noarch/pip/{{ trix_stream }}"
alertx_cli_pip: alertx-1.0-py3-none-any.whl

drainer_path: '/trinity/local/alertx_drainer'
daemon_path: '/trinity/local/alertx_drainer/daemon'

