---

alertx_packages: []

alertx_noarch_pip_repository: "https://updates.clustervision.com/trinityx/{{ trix_version }}/alertx/noarch/pip/{{ trix_stream }}"
alertx_cli_pip: alertx-1.0-py3-none-any.whl

alertx_drainer_path: '/trinity/local/alertx/drainer'
alertx_drainer_daemon_path: "{{ alertx_drainer_path }}/daemon"
alertx_drainer_ini_path: "/trinity/local/etc/alertx"
