---
# defaults for the init role

enable_selinux: false

init_packages:
  - python3-libselinux

cloud_support: ['azure', 'aws', 'gcp']

cloud_vpn_namekey:
  azure: vng_ip
  aws: vpn_tunnel1_ip
  gcp: vng_ip

cloud_vpn_pskkey:
  aws: vpn_tunnel1_preshared_key

cloud_vpn_espproposal:
  azure: aes256-sha1-modp1024
  aws: aes128-sha1-modp1024
  gcp: aes256-sha1-modp1024
