---
# tasks file for resolv

- name: Disable NetworkManager managing /etc/resolv.conf
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Render /etc/resolv.conf
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    backup: "yes"
  when: not ansible_virtualization_type=="docker"
