---

- name: Verify if /etc/hosts exists
  stat:
    path: /etc/hosts
  register: etc_hosts

- name: Create empty /etc/hosts
  file:
    path: /etc/hosts
    state: touch
  when: not etc_hosts.stat.exists

- block:
  - name: Set HA controllers' domain name
    blockinfile:
      path: /etc/hosts
      block: |
        {{trix_ctrl1_ip}}    {{trix_ctrl1_hostname}}.{{trix_domain}} {{trix_ctrl1_hostname}}
        {{trix_ctrl2_ip}}    {{trix_ctrl2_hostname}}.{{trix_domain}} {{trix_ctrl2_hostname}}
        {{trix_ctrl3_ip}}    {{trix_ctrl3_hostname}}.{{trix_domain}} {{trix_ctrl3_hostname}}
        {{trix_ctrl4_ip}}    {{trix_ctrl4_hostname}}.{{trix_domain}} {{trix_ctrl4_hostname}}
        {{trix_ctrl_ip}}    {{trix_ctrl_hostname}}.{{trix_domain}} {{trix_ctrl_hostname}}
    when: 
      - trix_ctrl3_ip is defined
      - trix_ctrl3_hostname is defined
      - trix_ctrl4_ip is defined
      - trix_ctrl4_hostname is defined

  - name: Set HA controllers' domain name
    blockinfile:
      path: /etc/hosts
      block: |
        {{trix_ctrl1_ip}}    {{trix_ctrl1_hostname}}.{{trix_domain}} {{trix_ctrl1_hostname}}
        {{trix_ctrl2_ip}}    {{trix_ctrl2_hostname}}.{{trix_domain}} {{trix_ctrl2_hostname}}
        {{trix_ctrl3_ip}}    {{trix_ctrl3_hostname}}.{{trix_domain}} {{trix_ctrl3_hostname}}
        {{trix_ctrl_ip}}    {{trix_ctrl_hostname}}.{{trix_domain}} {{trix_ctrl_hostname}}
    when: 
      - trix_ctrl3_ip is defined
      - trix_ctrl3_hostname is defined
      - (trix_ctrl4_ip is not defined) or (trix_ctrl4_hostname is not defined)

  - name: Set HA controllers' domain name
    blockinfile:
      path: /etc/hosts
      block: |
        {{trix_ctrl1_ip}}    {{trix_ctrl1_hostname}}.{{trix_domain}} {{trix_ctrl1_hostname}}
        {{trix_ctrl2_ip}}    {{trix_ctrl2_hostname}}.{{trix_domain}} {{trix_ctrl2_hostname}}
        {{trix_ctrl_ip}}    {{trix_ctrl_hostname}}.{{trix_domain}} {{trix_ctrl_hostname}}
    when: 
      - (trix_ctrl3_ip is not defined) or (trix_ctrl3_hostname is not defined)
      - (trix_ctrl4_ip is not defined) or (trix_ctrl4_hostname is not defined)
  when: ha|default(False)

- name: Set non-HA controller's domain name
  blockinfile:
    path: /etc/hosts
    block: |
      {{trix_ctrl_ip}}    {{trix_ctrl_hostname}}.{{trix_domain}} {{trix_ctrl_hostname}}
  when: not ha|default(False)

# Needs dnspython module. Available in RL,Alma,RH,C9, but not in 8. commented out for now. -Antoine
#- name: Verify if i can resolve trix_external_fqdn
#  set_fact:
#    trix_external_fqdn_resolvable: "{{ query('community.general.dig', trix_external_fqdn, '@'+trix_dns_forwarders|first) }}"
#
#- name: trix_external_fqdn warning
#  fail:
#    msg: "{{ trix_external_fqdn }} is not resolvable! Please add an entry for {{ trix_external_fqdn }} to /etc/hosts"
#  ignore_errors: true
#  when:
#    - trix_external_fqdn_resolvable is iterable
#    - '"NXDOMAIN" is in trix_external_fqdn_resolvable'

- name: Re-gather facts
  action: setup
