---

- name: Verify if /etc/hosts exists
  stat:
    path: /etc/hosts
  register: etc_hosts

- name: Create empty /etc/hosts
  file:
    path: /etc/hosts
    state: touch
  when: not etc_hosts.stat.exists

- debug:
    msg: "i am in HA mode"
  when: ha|default(False)

- name: Set HA controllers' domain name
  blockinfile:
    path: /etc/hosts
    block: |
      {{trix_ctrl1_ip}}    {{trix_ctrl1_hostname}}.{{trix_domain}} {{trix_ctrl1_hostname}}
      {{trix_ctrl2_ip}}    {{trix_ctrl2_hostname}}.{{trix_domain}} {{trix_ctrl2_hostname}}
      {{trix_ctrl_ip}}    {{trix_ctrl_hostname}}.{{trix_domain}} {{trix_ctrl_hostname}}
#      {{ ansible_default_ipv4.address }} {{ ansible_fqdn.split('.') | first }} {{ ansible_fqdn }}
  when: ha|default(False)

- name: Set non-HA controller's domain name
  blockinfile:
    path: /etc/hosts
    block: |
      {{trix_ctrl_ip}}    {{trix_ctrl_hostname}}.{{trix_domain}} {{trix_ctrl_hostname}}
#      {{ ansible_default_ipv4.address }} {{ ansible_fqdn.split('.') | first }} {{ ansible_fqdn }}
  when: not ha|default(False)


- name: Re-gather facts
  action: setup
