---

- name: Generate raw host list parser
  copy:
   src: 'rawhostlist.py'
   dest: '/usr/local/bin/rawhostlist.py'
   mode: 0755

- block:
  - name: Parse the raw host list
    shell: "/usr/local/bin/rawhostlist.py {{ rawhostlist }}"
    register: luna_parsed_hostlist

  - block:
    - name: Create nodes
      debug: 
        msg: "{{ luna_parsed_hostlist.stdout_lines }}"

    - name: Verify if cloudname/type exists
      shell: "luna cloud show {{ cloudname }}"
      register: luna_cloudname_exists
      ignore_errors: true

    - name: Create cloud
      shell: "luna cloud add -t {{ cloudtype }} {{ cloudname }}"
      when: luna_cloudname_exists.rc | int != 0

    - name: Verify if cloud group exists
      shell: "luna group show compute_{{ cloudname }}"
      register: luna_cloudgroup_exists
      ignore_errors: true

    - block:
      - name: generate part/post scripts
        copy:
          src: "{{ item }}"
          dest: "/tmp/{{ item }}"
        with_items:
          - part.rd
          - post.rd

      - name: Create cloud group
        shell: "luna group add -o compute -qpart /tmp/part.rd -qpost /tmp/post.rd compute_{{ cloudname }}"
      when: luna_cloudgroup_exists.rc | int != 0

    - name: Create nodes
      shell: "luna node add -g compute_{{ cloudname }} -cl {{ cloudname }} {{ item }}"
      with_items: "{{ luna_parsed_hostlist.stdout_lines }}"
      ignore_errors: true
    when:
      - luna_parsed_hostlist.rc | int == 0 
      - luna_parsed_hostlist.stdout_lines | length > 0

  when:
    - cloudname
    - cloudtype
    - rawhostlist
