---

- name: Generate raw host list parser
  copy:
   src: 'rawhostlist.py'
   dest: '/usr/local/bin/rawhostlist.py'
   mode: 0755

- block:
  - name: Parse the raw host list
    shell: "/usr/local/bin/rawhostlist.py {{ rawhostlist }}"
    register: luna_parsed_hostlist

  - block:
    - name: Create nodes
      debug: 
        msg: "{{ luna_parsed_hostlist.stdout_lines }}"

    - name: Create nodes
      shell: "echo {{ item }}"
      with_items: luna_parsed_hostlist.stdout_lines
    when:
      - luna_parsed_hostlist.rc | int == 0 
      - luna_parsed_hostlist.stdout_lines | length > 0

  when: rawhostlist
