---

- block:
  - name: Create Python Module under {{ trix_modulefiles }}
    template:
      src: 'ood-python-module.j2'
      dest: '{{ trix_shared }}/modulefiles/python'
      mode: '0644'
      owner: root
      group: root

  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    ansible.builtin.unarchive:
      src: https://github.com/OSC/bc_example_jupyter/archive/refs/tags/v1.0.1.zip
      dest: "{{ trix_ood }}/{{ ood_portal_version }}/trinity_jupyter"
      remote_src: yes

  - name: Set The Cluster Name
    lineinfile:
      dest: "{{ trix_ood }}/{{ ood_portal_version }}/trinity_jupyter/form.yml"
      regexp: '^.*cluster: (.*)$'
      line: 'cluster: "{{ ood_portal_cluster_name }}"'

  - name: Render submit rubby script
    template:
      src: 'submit.yml.erb'
      dest: "{{ trix_ood }}/{{ ood_portal_version }}/trinity_jupyter/submit.yml.erb"

  - name: Creating Symlink for Jupyter Notebook
    file:
      src: "{{ trix_ood }}/{{ ood_portal_version }}/trinity_jupyter"
      dest: "/var/www/ood/apps/sys/trinity_jupyter"
      state: link
      mode: 0755
      owner: root
      group: root
  when: 
    - on_controller|default(False)
    - ansible_connection not in 'chroot'

- block:
  - name: Install Jupyter Notebook Dependency
    shell: "apt-get -y install python3-pip"
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install Jupyter Notebook Dependency
    dnf:
      disable_gpg_check: true
      name: "python3-pip"
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Upgrade Python3-pip Version to support Jupyter Notebook Installation
    shell: "pip3 install --upgrade pip"
    ignore_errors: true

  - name: Uninstall clashing python packages
    dnf:
      name: '{{ item }}'
      state: removed
    with_items:
      - python3-packaging
      - python3-requests
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install Jupyter Notebook
    shell: "pip3 install {{ item }}"
    with_items:
      - notebook
      - ipyparallel
    ignore_errors: true
  when: ansible_connection in 'chroot'

