---
- block:
  - name: Create environment module for Jupyter Notebook Interactive App to load Python virtual environment
    template:
      src: 'ood-jupyter-python-module.j2'
      dest: '{{ trix_shared }}/modulefiles/ood-jupyter-python'
      mode: '0644'
      owner: root
      group: root

  - name: Clone git repository for Jupyter Notebook Interactive App
    git:
      repo: https://github.com/OSC/bc_example_jupyter.git
      dest: "{{ trix_ood }}/{{ ood_portal_version }}/trinity_jupyter"
      force: true

  - name: Set cluster name for Jupyter Notebook Interactive App
    lineinfile:
      dest: "{{ trix_ood }}/{{ ood_portal_version }}/trinity_jupyter/form.yml"
      regexp: '^.*cluster: (.*)$'
      line: 'cluster: "{{ ood_portal_cluster_name }}"'

  - name: Render submit script for Jupyter Notebook Interactive App
    template:
      src: 'submit.yml.erb'
      dest: "{{ trix_ood }}/{{ ood_portal_version }}/trinity_jupyter/submit.yml.erb"

  - name: Creating Symlink for Jupyter Notebook Interactive App
    file:
      src: "{{ trix_ood }}/{{ ood_portal_version }}/trinity_jupyter"
      dest: "/var/www/ood/apps/sys/trinity_jupyter"
      state: link
      mode: 755
      owner: root
      group: root
  when:
  - on_controller|default(False)
  - ansible_connection not in 'chroot'

- block:
  - name: Install python3-pip dependency for Jupyter Notebook
    apt:
      name: python3-pip
      state: present
      update_cache: yes
    when: ansible_facts['os_family'] == 'Debian'

  - name: Install python3-pip dependency for Jupyter Notebook
    dnf:
      name: python3-pip
      state: present
      disable_gpg_check: true
    when: ansible_facts['os_family'] == "RedHat"
    retries: "{{ rpm_retries | default(3) }}"
    delay: "{{ rpm_delay | default(15) }}"

  - name: Create Python virtual environment for Jupyter Notebook
    shell: "python3 -m venv /opt/ood-jupyter-python"
    when: ansible_connection in 'chroot'

  - name: Update pip
    pip:
      name: pip
      state: latest
      virtualenv: /opt/ood-jupyter-python

  - name: Install pip packages dependencies for Jupyter Notebook
    pip:
      name:
      - notebook
      - ipyparallel
      virtualenv: /opt/ood-jupyter-python
  when: ansible_connection in 'chroot'
