---
# tasks file for ood-interactive_apps

- name: Install Jupyter Notebook
  ansible.builtin.include_tasks:
    file: jupyter.yml
  when: '"Jupyter Notebook" in ood_interactive_apps'
  tags: jupyter
