---
- name: Copy the prometheus_node_exporter systemd service file
  ansible.builtin.template:
    src: prometheus_node_exporter.service.j2
    dest: /etc/systemd/system/prometheus_node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus_node_exporter

- name: Create prometheus_node_exporter config directory
  ansible.builtin.file:
    path: "{{prometheus_node_exporter_config_dir}}"
    state: directory
    owner: root
    group: root
    mode: u+rwX,g+rwX,o=rX

- name: Copy the prometheus_node_exporter config file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{prometheus_node_exporter_config_dir}}/config.yaml"
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus_node_exporter

- name: Create textfile collector dir
  ansible.builtin.file:
    path: "{{ prometheus_node_exporter_db_dir }}"
    state: directory
    owner: "{{ prometheus_node_exporter_system_user }}"
    group: "{{ prometheus_node_exporter_system_group }}"
    mode: u+rwX,g+rwX,o=rX
  when: prometheus_node_exporter_db_dir | length > 0

- name: Allow prometheus_node_exporter port in SELinux on RedHat OS family
  community.general.seport:
    ports: "{{ prometheus_node_exporter_web_listen_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"

- name: Configure prometheus node-exporter if prometheus_node_exporter_sd_file is defined
  blockinfile:
    path: "{{ prometheus_node_exporter_sd_file }}"
    block: |
      - targets:
        - {{ ansible_fqdn }}:{{ prometheus_node_exporter_web_listen_port }}
        labels:
          exporter: node
      {% if ansible_hostname in (all_ctrl_hostnames|default([trix_ctrl_hostname])) %}
          luna_group: controller
          luna_role: controller
      {% endif %}
    marker: "### {mark} ANSIBLE MANAGED BLOCK ({{ ansible_fqdn }}.prometheus_node_exporter)"
  when:
    - prometheus_node_exporter_sd_file is defined
  
