---
- name: Create the prometheus_node_exporter group
  ansible.builtin.group:
    name: "{{ prometheus_node_exporter_system_group }}"
    state: present
    system: true
  when: prometheus_node_exporter_system_group != "root"

- name: Create the prometheus_node_exporter user
  ansible.builtin.user:
    name: "{{ prometheus_node_exporter_system_user }}"
    group: "{{ prometheus_node_exporter_system_group }}"
    groups: "{{ prometheus_node_exporter_additional_system_groups }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: prometheus_node_exporter_system_user != "root"

- name: Get binary
  when:
    - prometheus_node_exporter_binary_local_dir | length == 0
  block:

    - name: Download prometheus_node_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ prometheus_node_exporter_binary_url }}"
        dest: "/tmp/prometheus_node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ __prometheus_node_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack prometheus_node_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "/tmp/prometheus_node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ go_arch }}/node_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate prometheus_node_exporter binaries
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ go_arch }}/node_exporter"
        dest: "{{ prometheus_node_exporter_binary_install_dir }}/prometheus_node_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart prometheus-node-exporter
      when: not ansible_check_mode

- name: Propagate locally distributed prometheus_node_exporter binary
  ansible.builtin.copy:
    src: "{{ prometheus_node_exporter_binary_local_dir }}/prometheus_node_exporter"
    dest: "{{ prometheus_node_exporter_binary_install_dir }}/prometheus_node_exporter"
    mode: 0755
    owner: root
    group: root
  when:
    - prometheus_node_exporter_binary_local_dir | length > 0
  notify: restart prometheus-node-exporter

- name: Create log dir if prometheus_node_exporter_log_dir is defined
  ansible.builtin.file:
    path: "{{ prometheus_node_exporter_log_dir }}"
    state: directory
    mode: 0755
  when:
    - prometheus_node_exporter_log_dir is defined