---

# simple method to verify if a stage has passed.

- name: Get prepare
  stat:
    path: '/etc/trinity/{{ stage }}.done'
  register: stage_done

- block:
  - name: Verify if prepare was run prior to playbook
    fail:
      msg: "prepare.sh did not run or did not complete. Please run prepare.sh till completion first"
    when: stage == "prepare"

  - name: Verify if controller playbook was run prior to playbook
    fail:
      msg: "ansible-playbook controller.yml was not run or did not complete. Please run the controller playbook till completion first"
    when: stage == "controller"
  when: not stage_done.stat.exists

# - name: Get Ansible Core Version
#   shell: ansible --version | head -n1 | cut -d ']' -f1 | awk '{print $3}'
#   register: ansible_version_output
#   changed_when: false
#
# - name: Check if Ansible Core version is less than 2.15
#   set_fact:
#     ansible_version_lt_215: "{{ ansible_version_output.stdout.split('.') | map('int') | list < [2, 15] }}"
#
# - name: Fail if Ansible Core version is less than 2.15
#   assert:
#     that:
#       - ansible_version_lt_215 == false
#     fail_msg: "Your Ansible Core version is {{ ansible_version_output.stdout }}. Please upgrade to at least version 2.15."
#     success_msg: "Ansible Core version is adequate ({{ ansible_version_output.stdout }})."
