---

# running inside chroot !!

- block:
  - name: Read facts
    slurp:
      src: /facts.dat
    register: slurp_output

  - name: Load facts
    set_fact:
      data: "{{ slurp_output['content'] | b64decode }}"

#  - name: Display facts
#    debug:
#      var: data

  - name: Set trix_ctrl_hostname fact
    set_fact:
       trix_ctrl_hostname: "{{ data['trix_ctrl_hostname'] }}"

  - name: Set trix_ctrl_ip fact
    set_fact:
       trix_ctrl_ip: "{{ data['trix_ctrl_ip'] }}"

  - name: Set luna_username fact
    set_fact:
       luna_username: "{{ data['luna_username'] }}"

  - name: Set luna_password fact
    set_fact:
       luna_password: "{{ data['luna_password'] }}"

  - name: Set luna_secret_key fact
    set_fact:
       luna_secret_key: "{{ data['luna_secret_key'] }}"

  - name: Set luna_protocol fact
    set_fact:
       luna_protocol: "{{ data['luna_protocol'] }}"

  - name: Set trix_domain fact
    set_fact:
       trix_domain: "{{ data['trix_domain'] }}"

  - name: Set luna_verify_certificate fact
    set_fact:
       luna_verify_certificate: "{{ data['luna_verify_certificate'] }}"

  - name: Set trix_stream fact
    set_fact:
       trix_stream: "{{ data['trix_stream'] }}"

  - name: Set system_arch fact
    set_fact:
       system_arch: "{{ data['system_arch'] }}"

  - name: Set package_arch fact
    set_fact:
       package_arch: "{{ data['package_arch'] }}"


  - debug:
      msg: "trix_ctrl_hostname: {{ trix_ctrl_hostname }}, trix_ctrl_ip: {{ trix_ctrl_ip }}"

  - name: Remove no longer needed facts file
    file:
      path: /facts.dat
      state: absent

  when: in_image

