
- name: Create trinityx-ood directory
  file:
    path: "{{ trix_ood }}/{{ ood_version }}"
    state: directory
    mode: 0755
    owner: root
    group: "{{ ood_admin_group }}"

- block:
  - name: Download and Unpack trinityx-ood custom apps
    ansible.builtin.unarchive:
      src: "/tmp/{{ ood_download_url.split('/') | last }}"
      dest: "{{ trix_ood }}"
      remote_src: yes

  - name: Symlink to current build
    file:
      state: link
      src: "{{ trix_ood }}/{{ ood_download_lead_path.stdout }}"
      dest: "{{ trix_ood }}/{{ ood_version }}"
      force: yes
  
  - name: Reset luna app directory permissions
    file:
      state: directory
      mode: u=rw,g=r,o=r,a-x+X



- name: Create trinityx-ood luna2 app config directory
  file:
    path: '{{ trix_ood }}/{{ ood_version }}/config/'
    state: directory
    mode: 0755
    owner: root
    group: "{{ ood_admin_group }}"

- name: Render trinityx-ood luna app luna.ini
  template:
    src: 'luna2.ini.j2'
    dest: '{{ trix_ood }}/{{ ood_version }}/config/luna.ini'
    owner: root
    group: "{{ ood_admin_group }}"
    mode: 0640

- name: Install trinityx-ood custom apps python requirements
  ansible.builtin.pip:
    requirements: "{{ trix_ood }}/{{ ood_version }}/{{ item }}/requirements.txt"
    virtualenv: /trinity/local/python/
  with_items: "{{ ood_custom_apps }}"

- name: Create custom app folders if they do not exist
  file:
    path: '/var/www/ood/apps/sys/{{ item | basename | regex_replace("\_manifest.yml.j2$", "") }}'
    state: directory
    mode: 0755
    owner: root
    group: "{{ ood_admin_group }}"
  notify: run update_ood
  with_fileglob:
    - '../templates/manifests/*.yml.j2'
  tags:
    - ood-manifests
  
- name: Render custom manifests to create buttons in the menu
  template:
    src: '{{ item }}'
    dest: '/var/www/ood/apps/sys/{{ item | basename | regex_replace("\_manifest.yml.j2$", "") }}/manifest.yml'
    owner: root
    group: "{{ ood_admin_group }}"
    mode: 0644
  notify: run update_ood
  with_fileglob:
    - '../templates/manifests/*.yml.j2'
  tags:
    - ood-manifests
  
- name: Symlink trinityx-ood custom apps
  file:
    src: "{{ trix_ood }}/{{ ood_version }}/{{ item }}"
    dest: "/var/www/ood/apps/sys/trinity_{{ item }}"
    state: link
    mode: 0755
    owner: root
    group: root
  with_items: "{{ ood_custom_apps }}"
  notify: run update_ood


  # ----------------------------------------------------------------------
  # ensuring ood app root dir is open
- name: Set permissions for all ood apps root directory
  file:
    path: "{{ trix_ood }}/{{ ood_version }}"
    mode: 0755
    owner: root
    group: "{{ ood_admin_group }}"


- name: Set permissions for admin ood apps
  # ----------------------------------------------------------------------
  # master block for apps that require special access. NOT for common users.
  file:
    path: "{{ trix_ood }}/{{ ood_version }}/{{ item }}"
    mode: 0750
    owner: root
    group: "{{ ood_admin_group }}"
  with_items: "{{ ood_admin_apps }}"

- name: Set permissions for apps that can be accessed by users
  # ----------------------------------------------------------------------
  # permission to allow access to apps for everyone
  file:
    path: "{{ trix_ood }}/{{ ood_version }}/{{ item }}"
    mode: 0755
    owner: root
    group: "{{ ood_admin_group }}"
  with_items: "{{ ood_user_apps }}"

- name: Configure firewalld
  firewalld:
    state: enabled
    port: "{{ ood_port }}/tcp"
    permanent: "yes"
    immediate: "yes"

- name: Set permissions for inifinband related apps
  # ----------------------------------------------------------------------
  file:
    path: "/dev/infiniband/umad0"
    mode: 0660
    owner: root
    group: "{{ ood_admin_group }}"
  ignore_errors: true
