- when: ansible_connection not in 'chroot'
  block:

  - name: Create ood directory
    file:
      path: "{{ trix_ood }}/{{ ood_luna_apps_version }}"
      state: directory
      mode: 0755
      owner: root
      group: "{{ ood_admin_group }}"

  - name: Download and Unpack trinityx-ood custom apps
    ansible.builtin.unarchive:
      src: "{{ ood_luna_apps_url }}"
      dest: "{{ trix_ood }}/{{ ood_luna_apps_version }}"
      mode: u=rw,g=r,o=r,a-x+X
      remote_src: yes
      extra_opts:
        - --transform
        - s#trinityx-ood-[a-zA-Z0-9.]*/#/#g

  - name: Symlink to current build
    file:
      state: link
      src:  "{{ trix_ood }}/{{ ood_luna_apps_version }}"
      dest: "{{ trix_ood }}/latest"
      force: True
      follow: False
    register: ood_luna_apps_download

  - name: Create trinityx-ood luna2 app config directory
    file:
      path: '{{ trix_ood }}/latest/config/'
      state: directory
      mode: 0755
      owner: root
      group: "{{ ood_luna_apps_admin_group }}"

  - name: Render trinityx-ood luna app luna.ini
    template:
      src: 'luna2.ini.j2'
      dest: '{{ trix_ood }}/latest/config/luna.ini'
      owner: root
      group: "{{ ood_luna_apps_admin_group }}"
      mode: 0640

  - name: Install trinityx-ood custom apps python requirements
    ansible.builtin.pip:
      requirements: "{{ trix_ood }}/latest/{{ item.name }}/requirements.txt"
      virtualenv: /trinity/local/python/
    with_items: "{{ ood_luna_apps }}"

  - name: Create custom app folders if they do not exist
    file:
      path: '/var/www/ood/apps/sys/{{ item | basename | regex_replace("\_manifest.yml.j2$", "") }}'
      state: directory
      mode: 0755
      owner: root
      group: "{{ ood_luna_apps_admin_group }}"
    notify: run update_ood
    with_fileglob:
      - '../templates/manifests/*.yml.j2'
    tags:
      - ood-manifests
    
  - name: Render custom manifests to create buttons in the menu
    template:
      src: '{{ item }}'
      dest: '/var/www/ood/apps/sys/{{ item | basename | regex_replace("\_manifest.yml.j2$", "") }}/manifest.yml'
      owner: root
      group: "{{ ood_luna_apps_admin_group }}"
      mode: 0644
    notify: run update_ood
    with_fileglob:
      - '../templates/manifests/*.yml.j2'
    tags:
      - ood-manifests
    
  - name: Symlink trinityx-ood custom apps
    file:
      src: "{{ trix_ood }}/latest/{{ item.name }}"
      dest: "/var/www/ood/apps/sys/trinity_{{ item.name }}"
      state: link
      mode: 0755
      owner: root
      group: root
    with_items: "{{ ood_luna_apps }}"
    notify: run update_ood

  - name: Configure firewalld
    firewalld:
      state: enabled
      port: "{{ ood_port }}/tcp"
      permanent: "yes"
      immediate: "yes"

  - name: Set permissions for inifinband related apps
    file:
      path: "/dev/infiniband/umad0"
      mode: 0660
      owner: root
      group: "{{ ood_luna_apps_admin_group }}"
    when: "'/dev/infiniband/umad0' is exists"
