---
# tasks file for ood-vnc

- name: Install ood-vnc requirements ( on machine whoose desktop is forwarded )
  block:
    - name: Rebuild RPM DB
      shell: "rpm --rebuilddb"
      ignore_errors: true

    - name: Install required yum repos
      dnf:
        name: "{{ item.name }}"
        state: present
        update_cache: true
        disable_gpg_check: "{{ item.no_gpgcheck | default(False) }}"
      with_items: "{{ ood_compute_repository_rpms }}"
      retries: "{{ rpm_retries | default(3) }}"
      delay: "{{ rpm_delay | default(15) }}"

    - name: Install required yum packages
      dnf:
        enablerepo: crb
        name:
          - "@{{ood_vnc_desktop_package}}"  # -> groupinstall xfce
          - turbovnc
          - python3-websockify
          - dbus-x11
        state: present
      retries: "{{ rpm_retries | default(3) }}"
      delay: "{{ rpm_delay | default(15) }}"

  when: enable_ood_vnc == true and ansible_connection in 'chroot'

# This should be done by controller because /trinity/shared is not mounted on compute node
- name: Render ood-vnc-module template file
  template:
    src: 'ood-vnc-module.j2'
    dest: '{{ trix_shared }}/modulefiles/ood-vnc'
    mode: '0644'
    owner: root
    group: root

  when: enable_ood_vnc == true and ansible_connection not in 'chroot'


# Fix xfce and other graphical environments using wayland instead of X11
- name: Override graphical environment scripts
  copy:
    src: script.sh.erb
    dest: /var/www/ood/apps/sys/bc_desktop/template/script.sh.erb
    mode: '0755'
    owner: root
    group: root

  when: enable_ood_vnc == true and ansible_connection not in 'chroot'
