---

- name: Install core packages - @core, kernel and grub2
  dnf:
    disable_gpg_check: true
    name: "{{ image_core_packages }}"
    state: present
    installroot: "{{ image_path }}"

- name: Install missing elfutils-libs on RedHat
  dnf:
    disable_gpg_check: true
    name: "elfutils-libs"
    state: present
    installroot: "{{ image_path }}"
  when: ansible_distribution == "RedHat"

