---
# Configure nscd daemon

- name: Install nscd
  yum:
    name: nscd
    state: present
  tags: install-only
  retries: "{{ network_retries | default(3) }}"
  delay: "{{ network_delay | default(15) }}"

- name: Put config file in place
  template:
    src: "nscd.conf.j2"
    dest: "/etc/nscd.conf"
  notify:
    - restart nscd

- name: Enable nscd service
  service:
    name: nscd
    enabled: "yes"
