---

required_packages:
  - "debootstrap"
  - "zstd"                                                                                                                                                                                   
                                                                                                                                                                                             
