- name: Configure password quality settings
  ansible.builtin.copy:
    dest: /etc/security/pwquality.conf
    content: |
      # /etc/security/pwquality.conf

      # Minimum acceptable size for the new password (8 characters)
      minlen = 8

      # Require at least 1 uppercase letter
      ucredit = -1

      # Require at least 1 lowercase letter
      lcredit = -1

      # Require at least 1 digit
      dcredit = -1

      # Require at least 1 special character
      ocredit = -1

      # Number of characters in the new password that must be different from the old password
      difok = 8
    owner: root
    group: root
    mode: '0644'